# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Chuu
tagline:          'Usurper of the pictures on the Internet'
description:      '<a href="https://www.instagram.com/jahcoozi/" target="_blank">@jahcoozi</a>'
#url:              http://hyde.getpoole.com
baseurl:          /

#author:
#  name:           'Alex Chuch'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
